// This file will be auto-generated by deploy script
const CONFIG = {
    CONTRACT_ADDRESS: '0xD768eC2DfAE881493Ced54bc59C691ccAaaF98fb',
    CONTRACT_ABI: [
        {
            "anonymous": false,
            "inputs": [
                {
                    "indexed": false,
                    "internalType": "string",
                    "name": "name",
                    "type": "string"
                },
                {
                    "indexed": false,
                    "internalType": "uint256",
                    "name": "seats",
                    "type": "uint256"
                },
                {
                    "indexed": false,
                    "internalType": "string[]",
                    "name": "prerequisites",
                    "type": "string[]"
                }
            ],
            "name": "CourseAdded",
            "type": "event"
        },
        {
            "anonymous": false,
            "inputs": [
                {
                    "indexed": false,
                    "internalType": "string",
                    "name": "reason",
                    "type": "string"
                }
            ],
            "name": "CourseAddError",
            "type": "event"
        },
        {
            "inputs": [
                {
                    "internalType": "string",
                    "name": "_name",
                    "type": "string"
                },
                {
                    "internalType": "uint256",
                    "name": "_availableSeats",
                    "type": "uint256"
                },
                {
                    "internalType": "string[]",
                    "name": "_prerequisites",
                    "type": "string[]"
                }
            ],
            "name": "addCourse",
            "outputs": [],
            "stateMutability": "nonpayable",
            "type": "function"
        },
        {
            "inputs": [
                {
                    "internalType": "address",
                    "name": "_student",
                    "type": "address"
                },
                {
                    "internalType": "string",
                    "name": "_courseName",
                    "type": "string"
                }
            ],
            "name": "completeCourse",
            "outputs": [],
            "stateMutability": "nonpayable",
            "type": "function"
        },
        {
            "inputs": [
                {
                    "internalType": "string",
                    "name": "_courseName",
                    "type": "string"
                }
            ],
            "name": "enroll",
            "outputs": [],
            "stateMutability": "nonpayable",
            "type": "function"
        },
        {
            "inputs": [],
            "name": "getAllCourses",
            "outputs": [
                {
                    "internalType": "string[]",
                    "name": "names",
                    "type": "string[]"
                },
                {
                    "internalType": "uint256[]",
                    "name": "seats",
                    "type": "uint256[]"
                },
                {
                    "internalType": "string[][]",
                    "name": "prereqs",
                    "type": "string[][]"
                },
                {
                    "internalType": "bool[]",
                    "name": "active",
                    "type": "bool[]"
                }
            ],
            "stateMutability": "view",
            "type": "function"
        },
        {
            "inputs": [
                {
                    "internalType": "string",
                    "name": "_courseName",
                    "type": "string"
                }
            ],
            "name": "getCourseDetails",
            "outputs": [
                {
                    "internalType": "string",
                    "name": "name",
                    "type": "string"
                },
                {
                    "internalType": "uint256",
                    "name": "availableSeats",
                    "type": "uint256"
                },
                {
                    "internalType": "string[]",
                    "name": "prerequisites",
                    "type": "string[]"
                },
                {
                    "internalType": "bool",
                    "name": "isActive",
                    "type": "bool"
                }
            ],
            "stateMutability": "view",
            "type": "function"
        },
        {
            "inputs": [
                {
                    "internalType": "address",
                    "name": "_student",
                    "type": "address"
                },
                {
                    "internalType": "string",
                    "name": "_courseName",
                    "type": "string"
                }
            ],
            "name": "hasCompletedPrerequisites",
            "outputs": [
                {
                    "internalType": "bool",
                    "name": "",
                    "type": "bool"
                }
            ],
            "stateMutability": "view",
            "type": "function"
        }
    ]
}; 